### ISSUE TITLE
Comment parsing

### ISSUE THREAD

**Issue by bnhovde** [animade/frontend-md#16]
Hi,

It would be really helpful with some config options for the comments parser. 

I'd love to use this for my projects but don't fancy changing my team's commenting style for it to work.

Here's an scss example module, whos comment won't be read. (probably due to the first line being blank)

``` scss

// *************************************
//
//   Example module
//   -> Overview of module and usage
//
// *************************************

// -------------------------------------
//   Base
// -------------------------------------

.module {

    // -------------------------------------
    //   Variables
    // -------------------------------------

    $module-var:    7em;
    $module-col-fg: #3B5998;
    $module-col-bg: #c0deed;


    // -------------------------------------
    //   Elements
    // -------------------------------------


    // ----- Element description ----- // 

    &__element {}


    // -------------------------------------
    //   Variations
    // -------------------------------------


    // ----- Variation description ----- // 

    &--variation {}

}
```
